baseurl = "https://aczane.netlify.com"
languageCode = "en-us"
title = "Is It Cake?"
copyright = "&copy; 2018 Ariel Zane"
theme = "hugo-lithium-theme"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/aczane"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/lariebyrd"

[params]
    description = "A data science blog"
    name = "Ariel Zane"
    disqusShortname = "is-it-cake"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    img = "/logo/portrait.png"
    url = "/"
    width = 50
    height = 50
    tag = ""

